### ISSUE TITLE
The queue may have a small bug?

### ISSUE THREAD

**Issue by yuanlin1991** [bkthomps/Containers#16]
Hello:
    I think the library is very useful and pretty good!But when I use the queue,I found a small bug,for example:
for(int i = 0;i<100;i++)
xxx;
{
queue_push();
queue_pop();
}
xxx;
In linux,the console is show Core Dump,the reason is "double free or corruption",the bug is place in the deque_trim() function.
Thank you very much!

**Comment by bkthomps** [comment]
Thank you for reporting this. I will take a look.

**Comment by bkthomps** [comment]
Hello, thank you for the bug report. I have made a change to fix this bug.

Before this bug was fixed, it would result in a segmentation fault due to an off-by-one error in the trim function in the deque file. This off by one error was due to the fact that the end index points to the index after the last allocated block. However, in the trim function, the end index was treated as the last allocated block. Thus, in the case that the last block was completely full, the trim function would function as if there were another block after that block with one item in it. Thus, this block would be copied from without the memory being allocated.

If you find any other bug or see that any improvements need to be made, please feel free to either create another issue or to contact me.
