### ISSUE TITLE
forward_list

### ISSUE THREAD

**Issue by angelskieglazki** [bkthomps/Containers#56]
`        free(backup->data);
        free(backup);
        if (!backup->next) {
            me->tail = NULL;
        }`

Do not you think that these lines(256-260) are a bit strange? For example, we refer to the pointer after the free function and set the tail to NULL
maybe it should look like this:
`       if (!backup->next) {
            me->tail = traverse;
        }
        free(backup->data);
        free(backup);
       `

**Comment by bkthomps** [comment]
Thank you for reporting this issue. You are right, as this is an invalid access. I'll create a fix for this soon.

**Comment by bkthomps** [comment]
The goal of the tail pointer is so that if we want to add to the end of the singly-linked list, it is O(1) and not O(n). However, if we remove the last element, we must invalidate the current tail by making it NULL. In this situation, I can fix this by moving the check to before the free.

**Comment by bkthomps** [comment]
Thank you for reporting the bug @angelskieglazki and the fix has been merged. I ran Valgrind on the codebase (a patch has been created so it works on MacOS Mojave now), and it seems that there are no more issues. If you find another issue, please feel free to report another one.

**Comment by angelskieglazki** [comment]
@bkthomps  if you add some printf to loop in function "forward_list_get_node_at"  and run this code

`#include <stdlib.h>
#include <stdio.h>
#include "containers.h"

void print_list(forward_list l)
{
    int i = 0;
    printf("List: ");
    for(i = 0; i <forward_list_size(l); ++i) {
        int elem = 0;
        forward_list_get_at(&elem, l, i);
        printf("%d ", elem);
    }
    printf("\n");
}

int main ()
{
    const int SIZE_LIST = 10;
    forward_list l = forward_list_init(sizeof(int));

    int i = 0;
    for (i = 0; i < SIZE_LIST; ++i) {
        forward_list_add_at(l, i, &i);
    }
    
    printf("Remove last\n");
    forward_list_remove_last(l);

    int res = 666;

    printf("Add last\n");
    forward_list_add_last(l, &res);
    return 0;
}
`

**Comment by bkthomps** [comment]
@angelskieglazki this is because of how the `forward_list` works. Getting at front is always O(1), getting in the middle (not tail and not head) is always O(n), and getting at back is either O(1) or O(n) based on if the tail pointer is valid (not NULL).

For example, as you mention, if you remove the last element, getting the last element will now be O(n). This is because the tail is invalid (NULL). However, if you add to the tail, or get/set at the tail, the tail pointer will now point to the last element, which means that you can get the last element in O(1).

The reason getting from the back is not always O(1) is because of the way a singly-list works: since elements only point to the next element, and not backwards, if I remove an element, I have no way of knowing what the element before it was.

A data structure which you can always access the last element in O(1) is a doubly-linked list, which is present in this library as `list`.

**Comment by angelskieglazki** [comment]
@bkthomps  Yes, of course, I know about all the classical data structures (thanks to the Kormen and Knuht). I just thought it would be better if each function preserves the invariants of the data structure after its execution. But this is your library and implementation is up to you. :)
Best regards.
